sudo: required

language: generic

matrix:
  include:
    # Build Linux wheels.
    - os: linux
      dist: trusty
      install:
        - mkdir .whl
        - touch .whl/asdf1

deploy:
  - provider: s3
    access_key_id: AKIAJ2L7XDUSZVTXI5QA
    secret_access_key:
      secure: M1693hcLmog1puS4Fzics8i+W76Nbt0ylzJQgl6fF7fVhgZruo/22dItNI1Ahxl/2fb6ft7h/JIY+DYSyz3rbkGNO+R5g3AqC6jejfDCwxlVsrwsyrN964UAMi7ZmAQ6S7O+473FqeUwPaMZRUwlUmm7dcdSWJ9+HICcbq8M4kNbCLRmwXW3DwvaAijIkZbCWl0mehqtnTU/iIKOJwHF+eg7LlFZ6p1bRpsgqDDyY4tIB3SCCtvpjjHrRjFAfe2flYH8wOmz21aSet98AgZYyCrEnKlu+vOrFfswzylZkji8cSwvOK2jKeauhgQkCiEGSZtI9Ua4x++VSwV8+bpiS2j4RA7qojVcPRqNShesRJ+S6OOTLQUOi0ELfdMXI9NPB5zJpqa1EWcNpmyOMRIvOy5ZmkjfdZ+97ETcakX/eKsmu9X4Q1Xcg9ns51STfV2NP1xLKPnD7XVBGHnT06PvF1r0JKM2tWuyV5Q8hFPYOhgcvvp0u4bVycHkS2dviSsfv+RiQVc3j9ogxtzbCtprksWGevoqKHhdxWx5Gw+CYGfLc0sMLIREiODfNORlVxcAexT8+qc0834aU7wD41ODFVao2bM38CjIodAcOz5eARgnaQ7lYsv/BKTrClxhp45TA4InPqqF6yrpdKF0/Jpu4wxHX50NZrEYnRg+v/dB+BU=
    bucket: ray-wheels
    acl: public_read
    region: us-west-2
    local_dir: .whl
    upload-dir: latest
    skip_cleanup: true
