sudo: required

language: generic

matrix:
  include:
    # Build Linux wheels.
    - os: linux
      dist: trusty
      install:
        - env
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_COMMIT_RANGE
        - echo $TRAVIS_COMMIT
